//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace honeyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaiLy
    {
        public string id { get; set; }
        public string id_khach_hang { get; set; }
        public int so_luong_tich_luy { get; set; }
        public string ghi_chu { get; set; }
    }
}
