//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace honeyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenMai
    {
        public string id { get; set; }
        public string name { get; set; }
        public System.DateTime thoi_gian_bat_dau { get; set; }
        public System.DateTime thoi_gian_ket_thuc { get; set; }
        public double ti_le_giam_gia { get; set; }
        public string ghi_chu { get; set; }
    }
}
