//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace honeyWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDatHang
    {
        public string id { get; set; }
        public string id_kh { get; set; }
        public string id_sp { get; set; }
        public int so_luong_sp { get; set; }
        public System.DateTime thoi_gian { get; set; }
        public int tinh_trang { get; set; }
    }
}
