//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace honeyWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class HoneyDBEntities : DbContext
    {
        public HoneyDBEntities()
            : base("name=HoneyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BaiViet> BaiViets { get; set; }
        public DbSet<ChiTietKhuyenMai> ChiTietKhuyenMais { get; set; }
        public DbSet<DaiLy> DaiLies { get; set; }
        public DbSet<DonDatHang> DonDatHangs { get; set; }
        public DbSet<KhachHang> KhachHangs { get; set; }
        public DbSet<KhuyenMai> KhuyenMais { get; set; }
        public DbSet<LoaiKhachHang> LoaiKhachHangs { get; set; }
        public DbSet<SanPham> SanPhams { get; set; }
        public DbSet<TinhTrangSanPham> TinhTrangSanPhams { get; set; }
        public DbSet<TrangThaiDonHang> TrangThaiDonHangs { get; set; }
    
        public virtual ObjectResult<GetAllArticles_Result> GetAllArticles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllArticles_Result>("GetAllArticles");
        }
    
        public virtual ObjectResult<GetAllProds_Result> GetAllProds()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllProds_Result>("GetAllProds");
        }
    
        public virtual ObjectResult<GetDetailProdById_Result> GetDetailProdById(string prodID)
        {
            var prodIDParameter = prodID != null ?
                new ObjectParameter("prodID", prodID) :
                new ObjectParameter("prodID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDetailProdById_Result>("GetDetailProdById", prodIDParameter);
        }
    
        public virtual ObjectResult<GetDetailProdByName_Result> GetDetailProdByName(string prodName)
        {
            var prodNameParameter = prodName != null ?
                new ObjectParameter("prodName", prodName) :
                new ObjectParameter("prodName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDetailProdByName_Result>("GetDetailProdByName", prodNameParameter);
        }
    }
}
