//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace honeyWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class HoneyDBEntities : DbContext
    {
        public HoneyDBEntities()
            : base("name=HoneyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BaiViet> BaiViets { get; set; }
        public DbSet<ChiTietKhuyenMai> ChiTietKhuyenMais { get; set; }
        public DbSet<DaiLy> DaiLies { get; set; }
        public DbSet<DonDatHang> DonDatHangs { get; set; }
        public DbSet<KhachHang> KhachHangs { get; set; }
        public DbSet<KhuyenMai> KhuyenMais { get; set; }
        public DbSet<LoaiKhachHang> LoaiKhachHangs { get; set; }
        public DbSet<SanPham> SanPhams { get; set; }
        public DbSet<TinhTrangSanPham> TinhTrangSanPhams { get; set; }
        public DbSet<TrangThaiDonHang> TrangThaiDonHangs { get; set; }
    
        public virtual ObjectResult<GetAllArticles_Result> GetAllArticles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllArticles_Result>("GetAllArticles");
        }
    
        public virtual ObjectResult<GetAllProds_Result> GetAllProds()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllProds_Result>("GetAllProds");
        }
    
        public virtual ObjectResult<GetDetailProdById_Result> GetDetailProdById(string prodID)
        {
            var prodIDParameter = prodID != null ?
                new ObjectParameter("prodID", prodID) :
                new ObjectParameter("prodID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDetailProdById_Result>("GetDetailProdById", prodIDParameter);
        }
    
        public virtual ObjectResult<GetDetailProdByName_Result> GetDetailProdByName(string prodName)
        {
            var prodNameParameter = prodName != null ?
                new ObjectParameter("prodName", prodName) :
                new ObjectParameter("prodName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDetailProdByName_Result>("GetDetailProdByName", prodNameParameter);
        }
    
        public virtual ObjectResult<GetAllArticles1_Result> GetAllArticles1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllArticles1_Result>("GetAllArticles1");
        }
    
        public virtual ObjectResult<GetAllProds1_Result> GetAllProds1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllProds1_Result>("GetAllProds1");
        }
    
        public virtual ObjectResult<GetDetailProdById1_Result> GetDetailProdById1(string prodID)
        {
            var prodIDParameter = prodID != null ?
                new ObjectParameter("prodID", prodID) :
                new ObjectParameter("prodID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDetailProdById1_Result>("GetDetailProdById1", prodIDParameter);
        }
    
        public virtual ObjectResult<GetDetailProdByName1_Result> GetDetailProdByName1(string prodName)
        {
            var prodNameParameter = prodName != null ?
                new ObjectParameter("prodName", prodName) :
                new ObjectParameter("prodName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDetailProdByName1_Result>("GetDetailProdByName1", prodNameParameter);
        }
    
        public virtual int AddNewCustomer(string id, string username, string password, string loaiKH, string hoten, string email, string sdt, string diachi)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var loaiKHParameter = loaiKH != null ?
                new ObjectParameter("loaiKH", loaiKH) :
                new ObjectParameter("loaiKH", typeof(string));
    
            var hotenParameter = hoten != null ?
                new ObjectParameter("hoten", hoten) :
                new ObjectParameter("hoten", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddNewCustomer", idParameter, usernameParameter, passwordParameter, loaiKHParameter, hotenParameter, emailParameter, sdtParameter, diachiParameter);
        }
    
        public virtual ObjectResult<GetCustomerById_Result> GetCustomerById(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCustomerById_Result>("GetCustomerById", idParameter);
        }
    
        public virtual int UpdateMarkCustomer(string id, Nullable<int> mark)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var markParameter = mark.HasValue ?
                new ObjectParameter("mark", mark) :
                new ObjectParameter("mark", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateMarkCustomer", idParameter, markParameter);
        }
    }
}
